# Generated by Django 2.0.6 on 2018-07-20 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_projectpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpost',
            name='on_going_project',
            field=models.CharField(choices=[('CPLT', 'Complete'), ('INC', 'Incomplete')], default='INC', max_length=4),
        ),
    ]
