# Generated by Django 2.0.6 on 2018-07-20 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_projectpost_on_going_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpost',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectpost',
            name='on_going_project',
            field=models.CharField(choices=[('CPLT', 'Complete'), ('INC', 'Incomplete'), ('DROP', 'Dropped')], default='INC', max_length=4),
        ),
    ]
