# Generated by Django 2.0.6 on 2018-07-27 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_aboutpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectpost',
            old_name='on_going_project',
            new_name='status',
        ),
    ]
