# Generated by Django 2.0.6 on 2018-07-27 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20180726_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpost',
            name='project_type',
            field=models.CharField(choices=[('GRP', 'Group'), ('INDV', 'Individual')], default='INDV', max_length=4),
        ),
    ]
