# Generated by Django 2.0.6 on 2018-07-27 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_projectpost_project_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutPost',
        ),
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('BLG', 'Blog'), ('ABT', 'About')], default='BLG', max_length=4),
        ),
    ]
