# Generated by Django 2.0.6 on 2018-07-27 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_highlights'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Highlights',
            new_name='Highlight',
        ),
    ]
