# Generated by Django 2.0.6 on 2018-07-27 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20180727_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlight',
            name='link',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
