# Generated by Django 2.0.6 on 2018-07-27 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20180727_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlight',
            name='highlight_type',
            field=models.CharField(choices=[('POST', 'Post'), ('PROJ', 'Projects'), ('RESU', 'Resume'), ('ABOT', 'About')], default='POST', max_length=4),
        ),
    ]
